name: 🙏🏻 Lint Test

on:
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
  workflow_dispatch:

jobs:
  lint-test:
    if: "! endsWith(github.actor, '[bot]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: projectdiscovery/actions/setup/go@v1

      - name: Run golangci-lint
        uses: projectdiscovery/actions/golangci-lint@v1